//HintName: Rocket.Surgery.MyAssembly/Rocket.Surgery.MyAssembly.ConstantsGenerator/Some.Nested.Root.Test.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     MyAssembly.Constants: 1.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

/// <summary>
/// Provides access to the current assembly information.
/// </summary>
partial class MyAssembly
{
    /// <summary>
    /// should be some
    /// </summary>
    public static partial class Some .

    Nested.Root {
    /// <summary>
    /// comment
    /// </summary>
    public const string Test = 
"""
Value
""";
} }
